name: Lint and Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: azure/setup-helm@v4

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Lint
        run: helm lint charts/node-local-dns

      - name: Unit tests
        run: helm unittest charts/node-local-dns
